// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkcbkbtfwgoghldrdvfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrY2JrYnRmd2dvZ2hsZHJkdmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0OTEzNjIsImV4cCI6MjA1NTA2NzM2Mn0.YsBcmPYgj0cFdLS6oF4lrL8hRwWH4Uv1GtAczDiuoXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);